project:
  type: website
website:
  navbar:
    logo: CSAFE_Tools_handwriter.png
    search: true
    left:
      - text: Home
        file: index.qmd
      - text: News
        file: NEWS.md
    right:
      - icon: github
        href: https://github.com/CSAFE-ISU/handwriter
        aria-label: handwriter GitHub
format:
  html:
    css: styles.css
    toc: true
    toc-depth: 2
    toc-location: left
