project:
  type: website

website:
  navbar:
    logo: "CSAFE_Tools_handwriter.png"
    search: true
    left:
      - text: Home
        file: index.qmd
      - text: News
        file: $ALTDOC_NEWS
      - text: License
        file: $ALTDOC_LICENSE
      - text: Citation
        file: $ALTDOC_CITATION
    right:
      - icon: github
        href: $ALTDOC_PACKAGE_URL_GITHUB
        aria-label: $ALTDOC_PACKAGE_NAME GitHub

format:
  html:
    css: csafe.css
    toc: true
    toc-depth: 3
    toc-location: left