---
title: "handwriter functions map"
author: "Stephanie Reinders"
date: "2024-04-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sdcHierarchies)
```

```{r}
h <- hier_create(root = "Total", nodes = c('processDocument'))

# processDocument
h <- hier_add(h, root = "processDocument", nodes = c("readPNGBinary", "thinImage", "processHandwriting"))
h <- hier_add(h, root = "processHandwriting", nodes = c("getNodes", 
                                                        "skeletonize",
                                                        "getComponents",
                                                        "mergeAllNodes",
                                                        "getPaths",
                                                        "getBreakPoints",
                                                        "addTroughNodes",
                                                        "updateBreakPoints",
                                                        "isolateGraphs",
                                                        "new_assign_sequential_ids",
                                                        "organizeLetters",
                                                        "createLetterLists",
                                                        "addCharacterFeatures",
                                                        'flatten_list'))
```

```{r}
h <- hier_add(h, root = 'getNodes', nodes = c('i_to_rc (1)', 
                                              'countChanges (nested)', 
                                              'node2by2fill (nested)'))
h <- hier_add(h, root = 'node2by2fill (nested)', nodes = c('findNeighbors (1)'))
```

```{r}
h <- hier_add(h, root = 'skeletonize', nodes = c('getSkeletonDF (nested)', 
                                                 'getSkeleton (1)'))
h <- hier_add(h, root = 'getSkeletonDF (nested)', nodes = c('i_to_rc (2)', 'findNeighbors (2)'))
```

```{r}
h <- hier_add(h, root = 'getComponents', nodes = c('initializeComponents (nested)',
                                                   'addSkeletons (nested)',
                                                   'addIndices (nested)',
                                                   'addNodes (nested)',
                                                   'addSkeleton0s (nested)',
                                                   'addAdjMatrices (nested)'))
h <- hier_add(h, root = 'addIndices (nested)', nodes = c('i_to_rc (3)'))
h <- hier_add(h, root = 'addSkeleton0s (nested)', nodes = c('getSkeletonDF0', 
                                                            'getSkeleton (2)'))
h <- hier_add(h, root = 'getSkeletonDF0', nodes = c('findNeighbors0'))
h <- hier_add(h, root = 'findNeighbors0', nodes = c('findNeighbors (3)'))
h <- hier_add(h, root = 'addAdjMatrices (nested)', nodes = c('getAdjMatrix (nested)'))
```

```{r}
h <- hier_add(h, root = 'mergeAllNodes', nodes = c('mergeNodes (nested)'))
h <- hier_add(h, root = 'mergeNodes (nested)', nodes = c('i_to_r (1)', 
                                                   'i_to_c (1)',
                                                   'findMergeNodes (nested in mergeAllNodes)', 
                                                'migrateConnections (nested in mergeAllNodes)'))
```

```{r}
h <- hier_add(h, root = 'getPaths', nodes = c('getAllNonLoopPaths (nested)', 
                                              'getAllLoops (nested)', 
                                              'updateAllSkeleton0s (nested)'))
h <- hier_add(h, root = 'getAllNonLoopPaths (nested)', nodes = c('getNonLoopPathsForComponent (nested in getPaths)'))
h <- hier_add(h, root = 'getAllLoops (nested)', nodes =  c('getLoopsForComponent (nested in getPaths'))
h <- hier_add(h, root = 'updateAllSkeleton0s (nested)', nodes = c('updateSkeleton0 (nested in getPaths)'))
```



```{r}
h <- hier_add(h, root = 'getBreakPoints', nodes = c('findTroughNodes'))
h <- hier_add(h, root = 'findTroughNodes', nodes = c('isTroughNode'))
h <- hier_add(h, root = 'addTroughNodes', nodes = c('i_to_r (2)', 'i_to_c (2)'))
h <- hier_add(h, root = 'updateBreakPoints', nodes = c('getNodeGraph', 'checkBreakPoints'))
h <- hier_add(h, root = 'isolateGraphs', nodes = c('makeGraphs', 'checkStacking', 'checkSimplicityBreaks'))
h <- hier_add(h, root = 'checkSimplicityBreaks', nodes = c('pathLetterAssociate (in checkSimplicityBreaks)'))
h <- hier_add(h, root = 'createLetterLists', nodes = c('pathLetterAssociate', 'nested_getConnectivity', 'getNodeOrder'))
h <- hier_add(h, root = 'getNodeOrder', nodes = c('nested_toRC'))
h <- hier_add(h, root = 'addCharacterFeatures', nodes = c('extract_character_features'))
h <- hier_add(h, root = 'extract_character_features', nodes = c('char_to_feature',
                                                                'add_updown_neighboring_char_dist',
                                                                'add_line_info', 
                                                                'nov_neighboring_char_dist', 
                                                                'add_covariance_matrix'))
h <- hier_add(h, root = 'char_to_feature', nodes = c('get_aspect_info', 'get_centroid_info'))
h <- hier_add(h, root = 'get_aspect_info', nodes = c('i_to_rci (1)'))
h <- hier_add(h, root = 'get_centroid_info', nodes = c('i_to_rci (2)', 'rc_to_i (1)'))
h <- hier_add(h, root = 'add_updown_neighboring_char_dist', nodes = c('i_to_rci (3)', 'rc_to_i (2)'))
h <- hier_add(h, root = 'add_line_info', nodes = c('line_number_extract', 'all_down_dists', 'all_centroids'))
h <- hier_add(h, root = 'line_number_extract', nodes = c('i_to_rci (4)'))
h <- hier_add(h, root = 'nov_neighboring_char_dist', nodes = c('character_features_by_line'))
h <- hier_add(h, root = 'add_covariance_matrix', nodes = c('i_to_rc (4)'))


```

```{r}
hier_display(h)
```





