
## Convert graph to a prototype {.unnumbered}


### Description

A graph prototype consists of the starting and ending points of each path in
the graph, as well as and evenly spaced points along each path. The prototype
also stores the center point of the graph. All points are represented as
xy-coordinates and the center point is at (0,0).



### Usage

<pre><code class='language-R'>graphToPrototype(graph, numPathCuts = 8)
</code></pre>


### Arguments

<table>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="graph">graph</code></td>
<td>
A graph from a handwriting sample
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="numPathCuts">numPathCuts</code></td>
<td>
Number of segments to cut the path(s) into
</td></tr>
</table>


### Value

List of pathEnds, pathQuarters, and pathCenters given as (x,y)
coordinates with the graph centroid at (0,0). The returned list also
contains path lengths. pathQuarters gives the (x,y) coordinates of the path
at the cut points and despite the name, the path might not be cut into
quarters.


