## Plot Template Cluster Centers {.unnumbered}


### Description

Plot the cluster centers of a cluster template created with
<code>make_clustering_template</code>. This function uses a K-Means type algorithm to
sort graphs from training documents into clusters. On each iteration of the
algorithm, it calculates the mean graph of each cluster and finds the graph
in each cluster that is closest to the mean graph. The graphs closest to the
mean graphs are used as the cluster centers for the next iteration.
Handwriter stores the cluster centers of a cluster template as graph
prototypes. A graph prototype consists of the starting and ending points of
each path in the graph, as well as and evenly spaced points along each path.
The prototype also stores the center point of the graph. All points are
represented as xy-coordinates and the center point is at (0,0).



### Usage

<pre><code class='language-R'>plot_cluster_centers(template, plot_graphs = FALSE, size = 100)
</code></pre>


### Arguments

<table>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="template">template</code></td>
<td>
A cluster template created with <code>make_clustering_template</code>
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="plot_graphs">plot_graphs</code></td>
<td>
TRUE plots all graphs in each cluster in addition to the
cluster centers. FALSE only plots the cluster centers.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="size">size</code></td>
<td>
The size of the output plot
</td></tr>
</table>


### Value

A plot



### Examples
```{r, warning=FALSE, message=FALSE, eval=TRUE}
library(handwriter)

# plot cluster centers from example template
plot_cluster_centers(example_cluster_template)
plot_cluster_centers(example_cluster_template, plot_graphs = TRUE)



```
