## Process Batch Directory {.unnumbered}


### Description

Process a list of handwriting samples saved as PNG images in a directory:
(1) Load the image and convert it to black and white with <code>readPNGBinary()</code>
(2) Thin the handwriting to one pixel in width with <code>thinImage()</code>
(3) Run <code>processHandwriting()</code> to split the handwriting into parts called <em>edges</em> and place <em>nodes</em> at the ends of
edges. Then combine edges into component shapes called <em>graphs</em>.
(4) Save the processed document in an RDS file.
(5) Optional. Return a list of the processed documents.



### Usage

<pre><code class='language-R'>process_batch_dir(input_dir, output_dir = ".", skip_docs_on_retry = TRUE)
</code></pre>


### Arguments

<table>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="input_dir">input_dir</code></td>
<td>
Input directory that contains images
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="output_dir">output_dir</code></td>
<td>
A directory to save the processed images
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="skip_docs_on_retry">skip_docs_on_retry</code></td>
<td>
Logical whether to skip documents in input_dir that
caused errors on a previous run. The errors and document names are stored
in output_dir &gt; problems.txt. If this is the first run,
<code>process_batch_list</code> will attempt to process all documents in input_dir.
</td></tr>
</table>


### Value

A list of processed documents



### Examples
```{r, warning=FALSE, message=FALSE, eval=FALSE}
library(handwriter)

process_batch_list("path/to/input_dir", "path/to/output_dir")
docs <- process_batch_list("path/to/input_dir", "path/to/output_dir")




```
