#========================================================
#============= ADDING TOOL TIPS TO UI ===================
#========================================================

#PRE PROCESSING 
addTooltip(session, id = 'rotation', title = "Slide to rotate document. Use arrows to adjust by 1 degree", options = list(delay = list(show=500)))
addTooltip(session, id = 'reset_crop', title = "Reset to originally uploaded image.", options = list(delay = list(show=500)))
addTooltip(session, id = 'undo_crop', title = "Undo previous crop", options = list(delay = list(show=500)))
addTooltip(session, id = 'crop', title = "Crop the highlighted area", options = list(delay = list(show=500)))
addTooltip(session, id = 'mask', title = "Mask the highlighted area", options = list(delay = list(show=500)))
addTooltip(session, id = 'undo_mask', title = "Undo previously applied mask", options = list(delay = list(show=500)))
addTooltip(session, id = 'reset_mask', title = "Undo all mask areas", options = list(delay = list(show=500)))
addTooltip(session, id = 'save_mask', title = "Save masks as an RData Object. The object will have the document and the mask, and must be saved with the .RData file type", options = list(delay = list(show=500)))

#PLOTTING
addTooltip(session, id = 'plot_processhandwriting', title = "Must be done before plotting. Can take up to a minute depending on the complexity of the document",
           placement = "bottom", trigger = "hover", options = list(delay = list(show=500)))
addTooltip(session, id = 'plotbinarized', title = "Plot the binarized (black and white) document", options = list(delay = list(show=500)))
addTooltip(session, id = 'plotthinned', title = "Plot the thinned version of the document", options = list(delay = list(show=500)))
addTooltip(session, id = 'plotnodes', title = "Plot the important nodes of the document", options = list(delay = list(show=500)))
addTooltip(session, id = 'plotbreaks', title = "Plot the break nodes of the document", options = list(delay = list(show=500)))
addTooltip(session, id = 'plotline', title = "Plot a given line of the document", options = list(delay = list(show=500)))
addTooltip(session, id = 'linenum', title = "Line number to plot", options = list(delay = list(show=500)))
addTooltip(session, id = 'plotword', title = "Plot a given word of the document", options = list(delay = list(show=500)))
addTooltip(session, id = 'wordnum', title = "Word number to plot", options = list(delay = list(show=500)))
addTooltip(session, id = 'plotgraph', title = "Plot a given graph of a document. Graphs are often, but not always, letters", options = list(delay = list(show=500)))
addTooltip(session, id = 'graphnum', title = "Graph number to plot", options = list(delay = list(show=500)))

#FEATURE EXPLORATION 
addTooltip(session, id = 'document_image', title = "A matrix reprsenting the cropped image, where 1s are the 'whitespace' and 0s represent the writing", options = list(delay = list(show=500)))
addTooltip(session, id = 'document_thin', title = "A list of the index values that are taken out during the thinning process", options = list(delay = list(show=500)))
addTooltip(session, id = 'document_nodes', title = "All points of importance to breaking apart graphs", options = list(delay = list(show=500)))
addTooltip(session, id = 'document_connectingNodes', title = "Nodes that are deemed to be connecting two graphs", options = list(delay = list(show=500)))
addTooltip(session, id = 'document_terminalNodes', title = "Nodes that are terminating on graphs", options = list(delay = list(show=500)))
addTooltip(session, id = 'document_breakPoints', title = "Based on nodes, points that are used to split apart two graphs", options = list(delay = list(show=500)))

addTooltip(session, id = 'graph_aspect_ratio', title = "Height to width ratio", options = list(delay = list(show=500)))
addTooltip(session, id = 'graph_height', title = "Height of the graph, measured in pixels", options = list(delay = list(show=500)))
addTooltip(session, id = 'graph_width', title = "Width of the graph, measured in pixels", options = list(delay = list(show=500)))
addTooltip(session, id = 'graph_topmost_row', title = "The top-most row, as its y coordinate", options = list(delay = list(show=500)))
addTooltip(session, id = 'graph_bottom_row', title = "The bottom-most row, as its y coordinate", options = list(delay = list(show=500)))
addTooltip(session, id = 'graph_leftmost_col', title = "The left-most column, as its x coordinate", options = list(delay = list(show=500)))
addTooltip(session, id = 'graph_rightmost_col', title = "The left-most column, as its x coordinate", options = list(delay = list(show=500)))
addTooltip(session, id = 'graph_centroid_index', title = "The centroid of the graph, as its index", options = list(delay = list(show=500)))
addTooltip(session, id = 'graph_centroid_y', title = "The y coordinate of the centroid", options = list(delay = list(show=500)))
addTooltip(session, id = 'graph_centroid_x', title = "The x coordinate of the centroid", options = list(delay = list(show=500)))
addTooltip(session, id = 'graph_horiz_location', title = "x", options = list(delay = list(show=500)))
addTooltip(session, id = 'graph_vert_location', title = "x", options = list(delay = list(show=500)))
addTooltip(session, id = 'graph_lHalf', title = "List of all points on the left half of the graph", options = list(delay = list(show=500)))
addTooltip(session, id = 'graph_rHalf', title = "List of all points on the right half of the graph", options = list(delay = list(show=500)))
addTooltip(session, id = 'graph_disjoint_centroids_left', title = "The centroids of the left half, as its index", options = list(delay = list(show=500)))
addTooltip(session, id = 'graph_disjoint_centroids_right', title = "The centroids of the right half, as its index", options = list(delay = list(show=500)))
addTooltip(session, id = 'graph_slope', title = "The slope of the graph as it runs through the centroid", options = list(delay = list(show=500)))
addTooltip(session, id = 'graph_pixel_density', title = "x", options = list(delay = list(show=500)))
addTooltip(session, id = 'graph_box_density', title = "x", options = list(delay = list(show=500)))
addTooltip(session, id = 'graph_uniqueid', title = "A unique numerical identifier for the graph", options = list(delay = list(show=500)))
addTooltip(session, id = 'graph_down_dist', title = "Distance from the lowest point of a graph to the next graph, measured in pixels", options = list(delay = list(show=500)))
addTooltip(session, id = 'graph_line_number', title = "The position of the graph in the line", options = list(delay = list(show=500)))
addTooltip(session, id = 'graph_order_within_line', title = "The ordered within the line the graph falls in", options = list(delay = list(show=500)))
addTooltip(session, id = 'graph_l_neighbor_dist', title = "Distance from the left-most point in the graph to its left neighbor, measured in pixels", options = list(delay = list(show=500)))
addTooltip(session, id = 'graph_r_neighbor_dist', title = "Distance from the right-most point in the graph to its left neighbor, measured in pixels", options = list(delay = list(show=500)))
addTooltip(session, id = 'graph_xvar', title = "Variance of X, used to calculate the covariance in covar", options = list(delay = list(show=500)))
addTooltip(session, id = 'graph_yvar', title = "Variance of Y, used to calculate the covariance in covar", options = list(delay = list(show=500)))
addTooltip(session, id = 'graph_covar', title = "Covarience of the graph", options = list(delay = list(show=500)))
addTooltip(session, id = 'graph_wordIndex', title = "Word number the graph belongs to", options = list(delay = list(show=500)))