// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// thinImage_c
arma::mat thinImage_c(arma::mat img);
RcppExport SEXP _handwriter_thinImage_c(SEXP imgSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type img(imgSEXP);
    rcpp_result_gen = Rcpp::wrap(thinImage_c(img));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_handwriter_thinImage_c", (DL_FUNC) &_handwriter_thinImage_c, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_handwriter(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
