# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' thinImage
#' 
#' This function returns a vector of locations for black pixels in the thinned image.
#' Thinning done using Zhang - Suen algorithm.
#'
#' @param img A binary matrix of the text that is to be thinned.
#' @export
thinImage <- function(img) {
    .Call('_handwriter_thinImage', PACKAGE = 'handwriter', img)
}

