# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:

name: R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}
          - {os: windows-latest, r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4
      
      - name: Install system dependencies (Ubuntu)
        if: runner.os == 'Ubuntu'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgsl-dev

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
      
      - name: Install JAGS (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install jags
          echo "JAGS_HOME=$(brew --prefix jags)" >> $GITHUB_ENV
      
      - name: Install JAGS (Windows)
        if: runner.os == 'Windows'
        run: |
          # Create a temporary directory for the installer
          $tempDir = Join-Path $env:RUNNER_TEMP "jags-installer"
          New-Item -ItemType Directory -Path $tempDir -Force
          
          # Download JAGS to the temporary directory
          $installerPath = Join-Path $tempDir "JAGS-4.3.1.exe"
          curl -LO https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/Windows/JAGS-4.3.1.exe
          Move-Item -Path "JAGS-4.3.1.exe" -Destination $installerPath
          
          # Install JAGS
          Start-Process -FilePath $installerPath -ArgumentList "/S" -NoNewWindow -Wait
          
          # Set environment variable
          echo "JAGS_HOME=C:/Program Files/JAGS/JAGS-4.3.1" >> $env:GITHUB_ENV
          
          # Clean up the installer
          Remove-Item -Path $tempDir -Recurse -Force
        shell: pwsh
      
      - name: Set up JAGS environment (macOS)
        if: runner.os == 'macOS'
        run: |
          echo "JAGS_LIB=$JAGS_HOME/lib" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$JAGS_HOME/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
          echo "LDFLAGS=-L$JAGS_HOME/lib" >> $GITHUB_ENV
          echo "CPPFLAGS=-I$JAGS_HOME/include" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$JAGS_HOME/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "DYLD_LIBRARY_PATH=$JAGS_HOME/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
          # Create symbolic links for JAGS modules
          sudo mkdir -p /usr/local/lib/JAGS/modules-4
          for module in basemod bugs terminal; do
            sudo ln -sf "$JAGS_HOME/lib/JAGS/modules-4/${module}.so" "/usr/local/lib/JAGS/modules-4/${module}.so"
          done
      
      - name: Set up JAGS environment (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "PATH=C:/Program Files/JAGS/JAGS-4.3.1/bin;${env:PATH}" >> $env:GITHUB_ENV
        shell: pwsh

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'